"""
Central place to store all supported asset URLs.

This keeps `news_fetching.py` smaller and makes it easy to add/maintain symbols.
"""

from __future__ import annotations

from typing import Dict, List


# -----------------------------
# FX pairs
# -----------------------------

SUPPORTED_PAIRS: Dict[str, Dict[str, str]] = {
    "EUR/USD": {
        "investing_url": "https://www.investing.com/currencies/eur-usd-news",
        "marketwatch_url": "https://www.marketwatch.com/investing/currency/eurusd",
        "yahoo_url": "https://finance.yahoo.com/quote/EURUSD=X/",
    },
    "USD/JPY": {
        "investing_url": "https://www.investing.com/currencies/usd-jpy-news",
        "marketwatch_url": "https://www.marketwatch.com/investing/currency/usdjpy",
        "yahoo_url": "https://finance.yahoo.com/quote/JPY=X/",
    },
    "GBP/USD": {
        "investing_url": "https://www.investing.com/currencies/gbp-usd-news",
        "marketwatch_url": "https://www.marketwatch.com/investing/currency/gbpusd",
        "yahoo_url": "https://finance.yahoo.com/quote/GBPUSD=X/",
    },
    "USD/CNY": {
        "investing_url": "https://www.investing.com/currencies/usd-cny-news",
        "marketwatch_url": "https://www.marketwatch.com/investing/currency/usdcny",
        "yahoo_url": "https://finance.yahoo.com/quote/CNY=X/",
    },
    "USD/CAD": {
        "investing_url": "https://www.investing.com/currencies/usd-cad-news",
        "marketwatch_url": "https://www.marketwatch.com/investing/currency/usdcad",
        "yahoo_url": "https://finance.yahoo.com/quote/CAD=X/",
    },
    "AUD/USD": {
        "investing_url": "https://www.investing.com/currencies/aud-usd-news",
        "marketwatch_url": "https://www.marketwatch.com/investing/currency/audusd",
        "yahoo_url": "https://finance.yahoo.com/quote/AUDUSD=X/",
    },
}


# -----------------------------
# NASDAQ 100 
# -----------------------------

NASDAQ_100_SYMBOLS: List[str] = [
    "NVDA",
    "MSFT",
    "AAPL",
    "GOOG",
    "GOOGL",
    "AMZN",
    "META",
    "AVGO",
    "TSLA",
    "NFLX",
    "PLTR",
    "COST",
    "ASML",
    "AMD",
    "CSCO",
    "AZN",
    "TMUS",
    "MU",
    "LIN",
    "PEP",
    "SHOP",
    "APP",
    "INTU",
    "AMAT",
    "LRCX",
    "PDD",
    "QCOM",
    "ARM",
    "INTC",
    "BKNG",
    "AMGN",
    "TXN",
    "ISRG",
    "GILD",
    "KLAC",
    "PANW",
    "ADBE",
    "HON",
    "CRWD",
    "CEG",
    "ADI",
    "ADP",
    "DASH",
    "CMCSA",
    "VRTX",
    "MELI",
    "SBUX",
    "CDNS",
    "ORLY",
    "SNPS",
    "MSTR",
    "MDLZ",
    "ABNB",
    "MRVL",
    "CTAS",
    "TRI",
    "MAR",
    "MNST",
    "CSX",
    "ADSK",
    "PYPL",
    "FTNT",
    "AEP",
    "WDAY",
    "REGN",
    "ROP",
    "NXPI",
    "DDOG",
    "AXON",
    "ROST",
    "IDXX",
    "EA",
    "PCAR",
    "FAST",
    "EXC",
    "TTWO",
    "XEL",
    "ZS",
    "PAYX",
    "WBD",
    "BKR",
    "CPRT",
    "CCEP",
    "FANG",
    "TEAM",
    "CHTR",
    "KDP",
    "MCHP",
    "GEHC",
    "VRSK",
    "CTSH",
    "CSGP",
    "KHC",
    "ODFL",
    "DXCM",
    "TTD",
    "ON",
    "BIIB",
    "LULU",
    "CDW",
    "GFS",
]


def _default_stock_urls(symbol: str) -> Dict[str, str | None]:
    # MarketWatch + Yahoo are consistent URL patterns by symbol.
    return {
        # Investing.com equity *news* URLs are slug-based (not symbol-based),
        # so we keep this as None for most tickers unless we have a known slug.
        "investing_url": None,
        "marketwatch_url": f"https://www.marketwatch.com/investing/stock/{symbol.lower()}",
        "yahoo_url": f"https://finance.yahoo.com/quote/{symbol}/",
    }


SUPPORTED_STOCKS: Dict[str, Dict[str, str | None]] = {
    sym: _default_stock_urls(sym) for sym in NASDAQ_100_SYMBOLS
}


# Known Investing.com equity news URL overrides (slug-based).
# Add more here over time if you want Investing.com coverage for more tickers.
_INVESTING_NEWS_OVERRIDES: Dict[str, str] = {
    "NVDA": "https://www.investing.com/equities/nvidia-corp-news",
    "MSFT": "https://www.investing.com/equities/microsoft-corp-news",
    "AAPL": "https://www.investing.com/equities/apple-computer-inc-news",
    "GOOG": "https://www.investing.com/equities/google-inc-news",
    "GOOGL": "https://www.investing.com/equities/google-inc-news",
    "AMZN": "https://www.investing.com/equities/amazon-com-inc-news",
    "META": "https://www.investing.com/equities/facebook-inc-news",
    "AVGO": "https://www.investing.com/equities/broadcom-corp-news",
    "TSLA": "https://www.investing.com/equities/tesla-motors-news",
    "NFLX": "https://www.investing.com/equities/netflix,-inc.-news",
    "PLTR": "https://www.investing.com/equities/palantir-technologies-inc-news",
    "COST": "https://www.investing.com/equities/costco-whsl-corp-new-news",
    "ASML": "https://www.investing.com/equities/asml-holding-nv-news",
    "AMD": "https://www.investing.com/equities/adv-micro-device-news",
    "CSCO": "https://www.investing.com/equities/cisco-sys-inc-news",
    "AZN": "https://www.investing.com/equities/astrazeneca-plc-news",
    "TMUS": "https://www.investing.com/equities/t-mobile-us-inc-news",
    "MU": "https://www.investing.com/equities/micron-tech-inc-news",
    "LIN": "https://www.investing.com/equities/linde-plc-news",
    "PEP": "https://www.investing.com/equities/pepsico-inc-news",
    "SHOP": "https://www.investing.com/equities/shopify-inc-news",
    "APP": "https://www.investing.com/equities/applovin-corp-news",
    "INTU": "https://www.investing.com/equities/intuit-inc-news",
    "AMAT": "https://www.investing.com/equities/applied-materials-inc-news",
    "LRCX": "https://www.investing.com/equities/lam-research-corp-news",
    "PDD": "https://www.investing.com/equities/pinduoduo-inc-ads-news",
    "QCOM": "https://www.investing.com/equities/qualcomm-inc-news",
    "ARM": "https://www.investing.com/equities/arm-holdings-plc-news",
    "INTC": "https://www.investing.com/equities/intel-corp-news",
    "BKNG": "https://www.investing.com/equities/booking-holdings-inc-news",
    "AMGN": "https://www.investing.com/equities/amgen-inc-news",
    "TXN": "https://www.investing.com/equities/texas-instruments-inc-news",
    "ISRG": "https://www.investing.com/equities/intuitive-surgical-inc-news",
    "GILD": "https://www.investing.com/equities/gilead-sciences-inc-news",
    "KLAC": "https://www.investing.com/equities/kla-corp-news",
    "PANW": "https://www.investing.com/equities/palo-alto-networks-inc-news",
    "ADBE": "https://www.investing.com/equities/adobe-sys-inc-news",
    "HON": "https://www.investing.com/equities/honeywell-intl-inc-news",
    "CRWD": "https://www.investing.com/equities/crowdstrike-holdings-inc-news",
    "CEG": "https://www.investing.com/equities/constellation-energy-corp-news",
    "ADI": "https://www.investing.com/equities/analog-devices-inc-news",
    "ADP": "https://www.investing.com/equities/automatic-data-processing-inc-news",
    "DASH": "https://www.investing.com/equities/doordash-inc-news",
    "CMCSA": "https://www.investing.com/equities/comcast-corp-news",
    "VRTX": "https://www.investing.com/equities/vertex-pharmaceuticals-inc-news",
    "MELI": "https://www.investing.com/equities/mercadolibre-inc-news",
    "SBUX": "https://www.investing.com/equities/starbucks-corp-news",
    "CDNS": "https://www.investing.com/equities/cadence-design-systems-inc-news",
    "ORLY": "https://www.investing.com/equities/oreilly-automotive-inc-news",
    "SNPS": "https://www.investing.com/equities/synopsys-inc-news",
    "MSTR": "https://www.investing.com/equities/microstrategy-inc-news",
    "MDLZ": "https://www.investing.com/equities/mondelez-international-inc-news",
    "ABNB": "https://www.investing.com/equities/airbnb-inc-news",
    "MRVL": "https://www.investing.com/equities/marvell-tech-group-inc-news",
    "CTAS": "https://www.investing.com/equities/cintas-corp-news",
    "TRI": "https://www.investing.com/equities/toronto-dominion-bank-news",
    "MAR": "https://www.investing.com/equities/marriott-intl-inc-news",
    "MNST": "https://www.investing.com/equities/monster-beverage-corp-news",
    "CSX": "https://www.investing.com/equities/csx-corp-news",
    "ADSK": "https://www.investing.com/equities/autodesk-inc-news",
    "PYPL": "https://www.investing.com/equities/paypal-holdings-inc-news",
    "FTNT": "https://www.investing.com/equities/fortinet-inc-news",
    "AEP": "https://www.investing.com/equities/american-electric-power-co-inc-news",
    "WDAY": "https://www.investing.com/equities/workday-inc-news",
    "REGN": "https://www.investing.com/equities/regeneron-pharmaceuticals-inc-news",
    "ROP": "https://www.investing.com/equities/roper-technologies-inc-news",
    "NXPI": "https://www.investing.com/equities/nxp-semiconductors-nv-news",
    "DDOG": "https://www.investing.com/equities/datadog-inc-news",
    "AXON": "https://www.investing.com/equities/axon-enterprise-inc-news",
    "ROST": "https://www.investing.com/equities/ross-stores-inc-news",
    "IDXX": "https://www.investing.com/equities/idexx-laboratories-inc-news",
    "EA": "https://www.investing.com/equities/electronic-arts-inc-news",
    "PCAR": "https://www.investing.com/equities/paccar-inc-news",
    "FAST": "https://www.investing.com/equities/fastenal-company-news",
    "EXC": "https://www.investing.com/equities/exelon-corp-news",
    "TTWO": "https://www.investing.com/equities/take-two-interactive-software-inc-news",
    "XEL": "https://www.investing.com/equities/xcel-energy-inc-news",
    "ZS": "https://www.investing.com/equities/zs-associates-inc-news",
    "PAYX": "https://www.investing.com/equities/paychex-inc-news",
    "WBD": "https://www.investing.com/equities/warner-bros-discovery-inc-news",
    "BKR": "https://www.investing.com/equities/baker-hughes-co-news",
    "CPRT": "https://www.investing.com/equities/copart-inc-news",
    "CCEP": "https://www.investing.com/equities/coca-cola-european-partners-plc-news",
    "FANG": "https://www.investing.com/equities/diamondback-energy-inc-news",
    "TEAM": "https://www.investing.com/equities/atlassian-corp-plc-news",
    "CHTR": "https://www.investing.com/equities/charter-communications-inc-news",
    "KDP": "https://www.investing.com/equities/kellanova-news",
    "MCHP": "https://www.investing.com/equities/microchip-technology-inc-news",
    "GEHC": "https://www.investing.com/equities/ge-healthcare-technologies-inc-news",
    "VRSK": "https://www.investing.com/equities/verisk-analytics-inc-news",
    "CTSH": "https://www.investing.com/equities/cognizant-technology-solutions-corp-news",
    "CSGP": "https://www.investing.com/equities/co-star-group-inc-news",
    "KHC": "https://www.investing.com/equities/kraft-heinz-co-news",
    "ODFL": "https://www.investing.com/equities/old-dominion-freight-line-inc-news",
    "DXCM": "https://www.investing.com/equities/dexcom-inc-news",
    "TTD": "https://www.investing.com/equities/the-trade-desk-inc-news",
    "ON": "https://www.investing.com/equities/on-semiconductor-corp-news",
    "BIIB": "https://www.investing.com/equities/biogen-inc-news",
    "LULU": "https://www.investing.com/equities/lululemon-athletica-inc-news",
    "CDW": "https://www.investing.com/equities/cdw-corp-news",
    "GFS": "https://www.investing.com/equities/genesis-fs-card-services-inc-news"
}

for _sym, _url in _INVESTING_NEWS_OVERRIDES.items():
    if _sym in SUPPORTED_STOCKS:
        SUPPORTED_STOCKS[_sym]["investing_url"] = _url

